apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-service
  labels:
    app: nginx-lb-service
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  type: LoadBalancer
