apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-service-custom-ip
  labels:
    app: nginx-service
  annotations:
    metallb.universe.tf/address-pool: expensive
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  type: LoadBalancer
  loadBalancerIP: 192.168.1.161
  externalName: nginx.slh
