# This HelmChartConfig can be used to patch traefik v2 installation 
# on k3s to make it us an assigned ip address for metallb.
# 
# The default configuration values can be found here:
# v2: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
# v2 documentation can be found here: https://doc.traefik.io/traefik/
#
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system

spec:
  targetNamespace: kube-system
  valuesContent: |-
    image:
      name: "rancher/library-traefik"
    service:
      annotations:
        metallb.universe.tf/address-pool: expensive    
      spec:
        loadBalancerIP: "192.168.1.160"
