# The default configuration values can be found here:
# v2: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
# v2 documentation can be found here: https://doc.traefik.io/traefik/
#
# v1: https://github.com/helm/charts/blob/master/stable/traefik/values.yaml 
# https://github.com/helm/charts/tree/master/stable/traefik
# deprecated after chart 1.87.5/traefik 1.7.26
#
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system

spec:
  chart: traefik
  version: 1.87.5
# if uncommented causes problems
  repo: https://charts.helm.sh/stable
  targetNamespace: kube-system
  valuesContent: |-
    image: "traefik"
    rbac:
      enabled: true
    ssl:
      enabled: true
    metrics:
      prometheus:
        enabled: true
    service:
      annotations:
        metallb.universe.tf/address-pool: expensive    
      spec:
        loadBalancerIP: "192.168.1.160"
    kubernetes:
      ingressEndpoint:
        useDefaultPublishedService: true
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
