# The default configuration values can be found here:
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
#
# Documentation can be found here: https://doc.traefik.io/traefik/
#
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system

spec:
  chart: traefik
  version: 9.7.0
  repo: https://helm.traefik.io/traefik
  targetNamespace: kube-system
  valuesContent: |-
#    ssl:
#      enabled: true
#    kubernetes:
#      ingressEndpoint:
#        useDefaultPublishedService: true
    image:
      name: "traefik"
      tag: 2.3.1
    metrics:
      prometheus: {}
    service:
      annotations:
        metallb.universe.tf/address-pool: expensive    
      spec:
        loadBalancerIP: "192.168.1.160"
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
