- hosts: all
  tasks:
  - name: Set authorized key for configured host user copying it from current user
    authorized_key:
      user: "{{ ansible_user }}"
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
