apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: kube-system

spec:
  chart: metallb
  version: 2.0.3
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: metallb-system
  valuesContent: |-
    image:
      name: "metallb"
      tag: 0.9.5
#    tolerations:
#      - key: "CriticalAddonsOnly"
#        operator: "Exists"
#      - key: "node-role.kubernetes.io/master"
#        operator: "Exists"
#        effect: "NoSchedule"
