---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: expensive
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.160-192.168.1.191
  #- 192.168.1.0/25
  autoAssign: false
  #avoid-buggy-ips: true
