---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.192-192.168.1.255
  #- 192.168.1.128/25
  autoAssign: true
  #avoid-buggy-ips: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - default
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: expensive
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.160-192.168.1.191
  #- 192.168.1.0/25
  autoAssign: false
  #avoid-buggy-ips: true
